// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPrinters() {
  return window['go']['main']['App']['GetPrinters']();
}

export function SaveRecord(arg1, arg2) {
  return window['go']['main']['App']['SaveRecord'](arg1, arg2);
}
