// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPrinters():Promise<Array<main.Printer>>;

export function SaveRecord(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;
