// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRecord(arg1, arg2) {
  return window['go']['main']['App']['DeleteRecord'](arg1, arg2);
}

export function GetPrinters() {
  return window['go']['main']['App']['GetPrinters']();
}

export function ListRecords(arg1) {
  return window['go']['main']['App']['ListRecords'](arg1);
}

export function PrintEnvelope(arg1) {
  return window['go']['main']['App']['PrintEnvelope'](arg1);
}

export function SaveRecord(arg1, arg2) {
  return window['go']['main']['App']['SaveRecord'](arg1, arg2);
}

export function SaveTemplate() {
  return window['go']['main']['App']['SaveTemplate']();
}
